Add config values using env vars
Cisco-Talos/clamav-docker pull request #63
Opened 2024-10-01 12:52 UTC by Loki-Afro

supply configuration values using -e like `-e CLAMD_CONF_StreamMaxLength=3000M` to add/replace them in the config for clamd or `FRESHCLAM_CONF_xxx` respectably for freshclam

inspired by https://github.com/mko-x/docker-clamav/blob/136fd83e5a7bad2e63fc87497be45d11eb838e94/debian/buster/envconfig.sh#L17-L23

unfortunately only possible in privileged mode as one can and should not modify the configs as clamd user

fixes gh-27

2024-10-01 12:55 UTC, Loki-Afro commented
some  additional notes

- i wasn't sure where to change the entry point scripts if only the unstable or all versions .. thus i changed them all because you support them all (?) and i didn't saw any mentioning in the documentation on how to use for any version restrictions
- i needed to change the original code from mko-x slightly since here `sh` is used instead of `bash`  - hope you are fine with that :)

2024-10-07 15:13 UTC, Loki-Afro commented
hey @rsundriyal what do you think? :)

2024-10-14 18:02 UTC, rsundriyal requested changes
- Fix the regex pattern
- Fix the duplicate code for 1.4 release

2024-10-14 18:02 UTC, rsundriyal commented on clamav/1.0/alpine/scripts/docker-entrypoint.sh
> +    grep -q "^$TRIMMED " /etc/clamav/clamd.conf && \
Config files have variables commented thus it is not able to find anything with current pattern. Adding "#" makes it work. 

Similar changes need to be done in other places too.

2024-10-14 18:04 UTC, rsundriyal commented
> hey @rsundriyal what do you think? :)

The code looks fine. I have requested the changes which I have tested too. 

Please add the changes.

2024-10-21 13:32 UTC, rsundriyal commented
@Loki-Afro In case the notifications are missed. I need your feedback on it. 
Please take a look.

2024-10-25 14:58 UTC, micahsnyder commented
@Loki-Afro Can you please take a look at @rsundriyal's recommendations?  

If you don't have time to work on it anymore let us know and we'd be happy to make the necessary changes ourselves so we can merge the PR.

2024-11-21 23:15 UTC, micahsnyder commented
Replaced by #68

2024-11-21 23:15 UTC, closed without merging